# Pipeline

This chapter goes through the actual pipeline used to process the data and fit the models, starting with the raw biopsy images all the way through to the computation of posterior probability of positive interaction.

[TODO: pipeline image here]

## Image Pre-Processing

In order to classify individual cells in an image of a biopsy, a 
random forest model was trained with the help of a trained 
pathologist. [NUMBER] cells from Skin Cutaneous Melanoma (SCM) [VERIFY?] 
were classified by the pathologist as tumor, lymphocyte, or other. 
The morphological [AND OTHER?] features of those cells were measured 
and used to train the model.

High resolution images of SCM biopsies were obtained from The 
Cancer Genome Atlas. The model was used to classify individual 
cells in each biopsy into one of four categories: tumor cell, 
TIL, macrophage, or other. 

[This section will likely need to be checked/fleshed out by Santhoshi and Arvind, since we will need to explain in at least some detail how the image processing happened, how the classification model was trained, etc.]

